# Generated by Django 5.0.6 on 2024-06-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='sub_services',
            field=models.TextField(blank=True),
        ),
    ]
