# Generated by Django 5.0.6 on 2024-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0002_alter_prices_description_alter_prices_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='prices',
            field=models.CharField(max_length=200),
        ),
    ]
