# Generated by Django 5.0.6 on 2024-07-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0004_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
