# Generated by Django 5.0.6 on 2024-07-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0005_alter_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='sub_services',
        ),
        migrations.AddField(
            model_name='prices',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='prices',
            name='services',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
