# Generated by Django 5.0.6 on 2024-07-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0006_remove_prices_sub_services_prices_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='home_page_description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
