# Generated by Django 5.0.6 on 2024-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0007_descriptions_home_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='home_page_description_cs',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='home_page_description_en',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='home_page_description_ru',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='description_cs',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='description_en',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='description_ru',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='services_cs',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='services_en',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='services_ru',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
