# Generated by Django 5.0.6 on 2024-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0008_descriptions_home_page_description_cs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='prices_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='prices_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='prices_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
